### ISSUE TITLE
Feature request - get existing constraint

### ISSUE THREAD

**Issue by gerchicov-bp** [ManueGE/Maketa#2]
Why can't I write for example `view.mkt.height => constraint` instead of `view.mkt.height = 10 => constraint`?

**Comment by ManueGE** [comment]
I don't understand what you want to achieve. To be able to assign a constraint to a variable you need to set it first, so

```
view.mkt.height = 10 => constraint
```

 is the way to go. 

Could you elaborate it a little more?

**Comment by ManueGE** [comment]
Oh, I see your point now. It's not possible at the moment and probably it won't be possible never. 

It works in a similar way that the native `anchors`:

With anchors, you can do this:

```
let constraint = view.heightAnchor.constraint(equalToConstant: 10)
```

but no:

```
let constraint = view.heightAnchor
```

**Comment by gerchicov-bp** [comment]
@ManueGE I wanted to wrap your library for particular cases of my concrete project like method for "constraint to left, right, bottom + height constraint which is changeable outside". The only way I found is to use your library as is and return the changeable constraints as the result/in completion block.
But I hoped I can get a link to this recently created constraint separately from such wrap methods using your library

**Comment by ManueGE** [comment]
I'm afraid you can't. The only way to get the constraint is saving it when you create it using maketa. Even constraints added by maketa can't be retrieved after you create them unless you save it at that pooint, so there is no way to achieve this. So sorry.

**Comment by gerchicov-bp** [comment]
@ManueGE ok, what what about to remove `fileprivate` and `private` modifiers from properties (at least those properties which I could use to identify how and which constaint should I find by myself)?
The problem with these "private" modifiers is I haven't enough possibilities to achieve the behavior I need. I can't override properties/methods with such modifiers so the only way for me is to rewrite them directly in your code but so I lose the compatibility with your future updates

**Comment by ManueGE** [comment]
What properties do you need to be public?

**Comment by gerchicov-bp** [comment]
I can't specify all the properties which are better to be public.
I usually come across with `Edge` limitations. So what about to make public `constraintsPointer` (or even create a method which returns `[NSLayoutConstraint]`)? Maybe `Edges().view` should be public too

**Comment by ManueGE** [comment]
Sorry, I would need concrete examples of what you want to achieve in order to see if making the properties public will add an actual value to the library.

**Comment by gerchicov-bp** [comment]
ok let I close this issue and reopen it or create a new one if it is necessary
